<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php") ?>
<?php

$APPLICATION->SetTitle("Контакты");

?>
<?php $APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"contacts", 
	array(
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "35",
		"NEWS_COUNT" => "20",
		"SETTINGS_USE" => "Y",
		"REGIONALITY_USE" => "N",
		"REGIONALITY_PROPERTY" => "REGIONS",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "MAP",
			1 => "CITY",
			2 => "ADDRESS",
			3 => "PHONE",
			4 => "PHONE_TWO",
			5 => "EMAIL",
			6 => "WORK_TIME",
			7 => "",
		),
		"CHECK_DATES" => "N",
		"MAP_VENDOR" => "yandex",
		"CONTACT_ID" => "",
		"PROPERTY_MAP" => "MAP",
		"API_KEY_MAP" => "",
		"PROPERTY_STORE_ID" => "STORE_ID",
		"PROPERTY_CITY" => "CITY",
		"PROPERTY_ADDRESS" => "ADDRESS",
		"PROPERTY_PHONE" => "PHONE",
		"PROPERTY_EMAIL" => "EMAIL",
		"PROPERTY_WORK_TIME" => "WORK_TIME",
		"PROPERTY_OPENING_HOURS" => "OPENING_HOURS",
		"WEB_FORM_ID" => "2",
		"WEB_FORM_CONSENT_URL" => "/company/consent/",
		"SHOW_MAP" => "Y",
		"SHOW_FORM" => "Y",
		"SHOW_LIST" => "SHOPS",
		"TITLE_SHOW" => "Y",
		"TITLE_TEXT" => "",
		"DESCRIPTION_SHOW" => "Y",
		"DESCRIPTION_TEXT" => "",
		"DETAIL_URL" => "/contacts/stores/#ID#/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Контакты",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"FILE_404" => "/404.php",
		"COMPONENT_TEMPLATE" => "contacts",
		"PROPERTY_PHONE_TWO" => "PHONE_TWO"
	),
	false
); ?>
<?$APPLICATION->IncludeComponent(
	"intec.universe:main.form", 
	"template.1", 
	array(
		"CACHE_TIME" => "0",
		"CACHE_TYPE" => "A",
		"CONSENT" => "/company/consent/",
		"ID" => "2",
		"NAME" => "Обратная связь",
		"TEMPLATE" => ".default",
		"COMPONENT_TEMPLATE" => "template.1",
		"FORMS_1_ID" => "",
		"FORMS_2_ID" => "",
		"FORMS_1_NAME" => "",
		"FORMS_2_NAME" => "",
		"FORMS_1_BUTTON" => "Заказать звонок",
		"FORMS_2_BUTTON" => "Задать вопрос",
		"TITLE" => "Свяжитесь с нами",
		"DESCRIPTION_SHOW" => "N",
		"SETTINGS_USE" => "N",
		"LAZYLOAD_USE" => "N",
		"BUTTON_TEXT" => "Обратная связь",
		"THEME" => "dark",
		"VIEW" => "left",
		"BACKGROUND_COLOR" => "#f4f4f4",
		"BACKGROUND_IMAGE_USE" => "N",
		"BODY_TEXT" => "Только на конференции вы встречаетесь с экспертами, забираете их знания и получаете ответы на свои вопросы",
		"BODY_DESCRIPTION_SHOW" => "N",
		"BUTTON_POSITION" => "right",
		"BUTTON_UNDER_SHOW" => "N",
		"BACKGROUND_USE" => "N"
	),
	false
);?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>
